name: appsdk_v2_flutter_plugin_example
description: "Demonstrates how to use the appsdk_v2_flutter_plugin plugin."
publish_to: 'none'

environment:
  sdk: '>=3.10.0'
  flutter: '>=3.30.0'

dependencies:
  flutter:
    sdk: flutter
  appsdk_v2_flutter_plugin:
    path: ../
  ia_cardlink:
    path: ../modules/ia_cardlink
  ia_ordering:
    path: ../modules/ia_ordering
  ia_over_the_counter:
    path: ../modules/ia_over_the_counter
  ia_pharmacy:
    path: ../modules/ia_pharmacy
  ia_prescription:
    path: ../modules/ia_prescription
  flutter_web_browser: ^0.17.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - .secrets
    - .env