group = "com.example.appsdk_v2_flutter_plugin"
version = "1.0-SNAPSHOT"

buildscript {
    ext.kotlin_version = "2.1.0"
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
        }
        mavenLocal()
        maven {
            name = "IA SDK repo"
            url = uri("https://maven.pkg.github.com/ihreapotheken/IA-SDK-Android")
            credentials {
                username = System.getenv("GITHUB_USERNAME") ?: "mljubas@4ofthem.eu"
                password = System.getenv("GITHUB_TOKEN") ?: "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"
            }
        }
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.12.3")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.20"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"
apply plugin: "org.jetbrains.kotlin.plugin.compose"

android {
    namespace = "de.ihreapotheken.appsdk_v2_flutter_plugin"

    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 30
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}

dependencies {
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.mockito:mockito-core:5.20.0")
    def iaDeSdkVersion = "0.0.34-1"
    def iaDeSdkEnv = System.getenv("IA_DE_SDK_ENV") ?: ""
    def iaDeSdkDeps = [
            "de.ihreapotheken.sdk:integrations",
            "de.ihreapotheken.sdk:otc",
            "de.ihreapotheken.sdk:ordering",
            "de.ihreapotheken.sdk:pharmacy",
            "de.ihreapotheken.sdk:rx",
            "de.ihreapotheken.sdk:apofinder"
    ]
    iaDeSdkDeps.each { dep ->
        def fullDep = "${dep}${!iaDeSdkEnv.isBlank() ? "-${iaDeSdkEnv}" : ""}:${iaDeSdkVersion}"
        implementation fullDep
    }
    implementation("androidx.compose.material3:material3:1.3.1")
    implementation("androidx.compose.foundation:foundation-layout:1.7.6")
}