name: Demo App Deploy

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      - run: |
          printf '%s' "${{ secrets.ANDROID_FIREBASE_DISTRIBUTION_SERVICE_CREDENTIALS }}" \
          > example/android/fb-distribution-service-credentials.json
      - run: cat example/android/fb-distribution-service-credentials.json
      - run: echo "${{ secrets.ANDROID_SIGNING_KEY_DATA_BASE64 }}" | base64 --decode > example/android/demo.jks
      - run: echo "${{ secrets.ANDROID_SIGNING_KEY_PROPERTIES }}" > example/android/key.properties
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install Signing Certificate
        run: |
          CERT_PATH=$HOME/cert.p12
          echo ${{ secrets.IOS_SIGNING_CERT }} | base64 --decode > "$CERT_PATH"
          KEYCHAIN_PATH=$HOME/my.keychain-db
          APPLE_KEYCHAIN_PASSWORD="Password1!"
          security create-keychain -p "$APPLE_KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$APPLE_KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import "$CERT_PATH" -k "$KEYCHAIN_PATH" -P "" -A
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security set-key-partition-list \
            -S apple-tool:,apple:,codesign: \
            -s -k "$APPLE_KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo ${{ secrets.IOS_PROVISIONING_PROFILE }} | base64 --decode > \
            ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
        env:
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
      - run: sh scripts/deploy-demo.sh