name: Demo App Deploy

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: [self-hosted, macOS]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.ANDROID_FIREBASE_DISTRIBUTION_SERVICE_CREDENTIALS }}" | base64 --decode > example/android/fb-distribution-service-credentials.json
      - run: echo "${{ secrets.ANDROID_SIGNING_KEY_DATA_BASE64 }}" | base64 --decode > example/android/demo.jks
      - run: echo "${{ secrets.ANDROID_SIGNING_KEY_PROPERTIES }}" > example/android/key.properties
      - run: sh scripts/deploy-demo.sh